use evmole::compose::{
    ComposeValidationInput, VirtualStorageLayout, VirtualStorageLayoutKind,
    VirtualStorageLayoutRecord, VirtualStorageLayoutSource, validate_and_print,
};

fn record(
    id: &str,
    virtual_path: &str,
    kind: VirtualStorageLayoutKind,
    layout: Vec<&str>,
    slots: Vec<Vec<u16>>,
) -> VirtualStorageLayoutRecord {
    let layout = layout.into_iter().map(str::to_owned).collect::<Vec<_>>();
    let mut serialized_layout = vec!["0x01".to_owned()];
    serialized_layout.extend(layout.iter().cloned());

    VirtualStorageLayoutRecord {
        id: id.to_owned(),
        virtual_path: virtual_path.to_owned(),
        parent_virtual_path: None,
        kind,
        code_width: 1,
        layout,
        serialized_layout,
        slots,
        source: VirtualStorageLayoutSource::Erc8042,
        source_name: "tests/fixtures/FullStorageFacet.sol".to_owned(),
        contract_name: "FullStorageFacet".to_owned(),
        struct_name: Some("Storage".to_owned()),
        diamond_name: None,
    }
}

fn main() {
    // Generated from the canonical FullStorageFacet VSL fixture in the Compose CLI.
    let input = ComposeValidationInput {
        bytecode: Vec::new(),
        virtual_storage_layout: VirtualStorageLayout {
            records: vec![
                record(
                    "0x187161d428838e222a90f1affeed2c78fc4f4ebcd75b6865df1ab62fbe7ff88f",
                    "compose.fixture.virtual-storage",
                    VirtualStorageLayoutKind::Normal,
                    vec![
                        "0x01", "0x02", "0x03", "0x10", "0x11", "0x32", "0x51", "0x17", "0x72",
                        "0x73", "0x70", "0xf4", "0x53", "0xf4", "0x53", "0x13", "0xff", "0x13",
                        "0xff", "0xf1", "0x03", "0x2f", "0xff", "0xf1", "0x2f", "0xf2", "0x2f",
                        "0xff", "0xf2", "0x2f", "0xff", "0xf2", "0x10", "0xff", "0xf3", "0x01",
                        "0x05", "0x2f", "0xff", "0xf3", "0x02", "0x01", "0x2c", "0x2f", "0xff",
                        "0xf3", "0x01", "0x0a", "0xf3", "0x01", "0x05", "0x2f", "0xff", "0xf1",
                        "0x03", "0xff", "0xf2", "0xff", "0xf3", "0x01", "0x02", "0xff", "0xf1",
                        "0x2f", "0xf2", "0xff", "0xf1", "0x72", "0x2f", "0xff", "0xf1", "0x73",
                        "0x2f", "0xff", "0x71",
                    ],
                    vec![
                        vec![8, 8, 160, 8, 16, 24, 16],
                        vec![64],
                        vec![256],
                        vec![256],
                        vec![192],
                        vec![32],
                        vec![32, 32],
                        vec![32],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![256],
                        vec![8, 160],
                        vec![256],
                        vec![8, 160],
                        vec![256],
                        vec![256],
                        vec![256],
                    ],
                ),
                record(
                    "0x42c03859431109f7fad75350edc69aa1db562762f05fba0202a90bd84808ddd6",
                    "compose.fixture.virtual-storage.367",
                    VirtualStorageLayoutKind::Normal,
                    vec!["0x2f", "0x01", "0x03"],
                    vec![vec![256], vec![8, 160]],
                ),
                record(
                    "0xb51977e840a1651e6c8ef21d54c761bb4cb20c77ca792c87669ce16c0687099c",
                    "compose.fixture.virtual-storage.368",
                    VirtualStorageLayoutKind::Immutable,
                    vec!["0x2f", "0x01", "0x03"],
                    vec![vec![256], vec![8, 160]],
                ),
                record(
                    "0xc2fd5304c1323c6ba4b15d7c88c0d1777c1cdeea0e7838c8d5c472c6d1291134",
                    "compose.fixture.virtual-storage.369",
                    VirtualStorageLayoutKind::Immutable,
                    vec!["0x2f", "0x01", "0x03"],
                    vec![vec![256], vec![8, 160]],
                ),
                record(
                    "0xeb346c363747d0610fa1fa60cf518f0a5c41f9e361b08f6543f2dbb191d0c57e",
                    "compose.fixture.virtual-storage.373",
                    VirtualStorageLayoutKind::Immutable,
                    vec!["0x2f", "0x01", "0x03"],
                    vec![vec![256], vec![8, 160]],
                ),
            ],
        },
    };

    validate_and_print(&input);
}
